version: '3.9'
services:
  app:
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: crent
    network_mode: bridge
    links:
      - db
    ports:
      - 8080:8080
    expose:
      - 8080

  db:
    image: postgres:latest
    container_name: postgres_container
    network_mode: bridge
    environment:
      - POSTGRES_USER=admin  
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  