name: Build and Push to DockerHub

on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

jobs:
  build:
    name: Push Docker image to DockerHub and Deploy on an EC2 instance
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push to DockerHub
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: zittermann/crent:latest
        build-args: |
          SENTRY_DNS=${{ secrets.SENTRY_DNS }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
      
  deploy:
    name: Deploy on an EC2 Instance
    runs-on: ubuntu-latest
    steps:
      - name: AWS Credentials and Docker pull from DockerHub
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop crent || true
            docker rm crent || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/crent:latest
            docker run -d --name crent ${{ secrets.DOCKERHUB_USERNAME }}/crent:latest
        
        
