name: Build and Push to DockerHub

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and Push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        
      run: |
        docker buildx create --use
        echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
        docker buildx build --platform linux/amd64,linux/arm64 -t zittermann/crent:latest .
        docker push zittermann/crent:latest
      
