name: Build and Push Docker Image to DockerHub

on:
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and Push the Docker image
      uses: docker/build-push-action@v4
      with:
        context: /
        push: true
        tags: zittermann/crent:latest
