name: Build and Push to DockerHub

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Push Docker image to DockerHub and Deploy on an EC2 instance
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Configure Docker layer caching for pull requests
      run: |
        if [ -n "$CI_PULL_REQUEST" ]; then
          docker buildx create --use
          docker buildx inspect --bootstrap
        fi

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: zittermann/crent:latest
      
    - name: Deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker stop crent || true
          docker rm crent || true
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/crent:latest
          docker run -d --name crent ${{ secrets.DOCKERHUB_USERNAME }}/crent:latest
          
        
